package lz

import (
	"fmt"
	"math"
	"regexp"
	"strconv"
	"sync"
)

// bucketHash implements a bucketed hash table for the mapper. It stores up to
// bucketSize recent entries per hash value and maintains a circular index
// into each bucket to track insertion position. The structure stores pre-
// computed mask and shift values used for hashing.
type bucketHash struct {
	buckets    []Entry
	indexes    []byte
	mask       uint64
	shift      uint
	inputLen   int
	hashBits   int
	bucketSize int
}

// String returns the canonical name of the bucket hash configuration in the
// form "bucketHash_<inputLen>:<hashBits>:<bucketSize>".
func (bh *bucketHash) String() string {
	return fmt.Sprintf("bucketHash_%d:%d:%d",
		bh.inputLen, bh.hashBits, bh.bucketSize)
}

// bucketHashParams holds the configuration parameters used to construct a
// bucketHash: the inputLen (number of bytes considered for hashing), the
// number of hashBits defining the table size, and the bucketSize (number
// of entries stored per hash).
type bucketHashParams struct {
	inputLen   int
	hashBits   int
	bucketSize int
}

// verify validates the bucketHashParams ensuring values are within the
// supported ranges. It returns an error describing the constraint violation.
func (p *bucketHashParams) verify() error {
	if !(2 <= p.inputLen && p.inputLen <= 8) {
		return fmt.Errorf("lz: inputLen must be between 2 and 8")
	}
	maxHashBits := min(23, 8*p.inputLen)
	if !(0 <= p.hashBits && p.hashBits <= maxHashBits) {
		return fmt.Errorf("lz: hashBits must be between 0 and %d", maxHashBits)
	}
	if !(1 <= p.bucketSize && p.bucketSize <= 128) {
		return fmt.Errorf("lz: bucketSize must be between 1 and 128")
	}
	return nil
}

// bucketHashRegexp matches strings generated by bucketHash.String and is
// used by parseBucketHashName to extract parameters.
var bucketHashRegexp = sync.OnceValue(func() *regexp.Regexp {
	return regexp.MustCompile(`bucketHash_(\d+):(\d+):(\d+)`)
})

// parseBucketHashName parses a name produced by bucketHash.String and
// returns the corresponding bucketHashParams. It returns an error if the
// name is invalid or parameters are out of range.
func parseBucketHashName(name string) (p bucketHashParams, err error) {
	m := bucketHashRegexp().FindStringSubmatch(name)
	if m == nil {
		return bucketHashParams{},
			fmt.Errorf("lz: invalid bucketHash name: %s", name)
	}

	p.inputLen, err = strconv.Atoi(m[1])
	if err != nil {
		return bucketHashParams{}, fmt.Errorf(
			"lz: invalid inputLen in bucketHash name: %s", name)
	}
	p.hashBits, err = strconv.Atoi(m[2])
	if err != nil {
		return bucketHashParams{}, fmt.Errorf(
			"lz: invalid hashBits in bucketHash name: %s", name)
	}
	p.bucketSize, err = strconv.Atoi(m[3])
	if err != nil {
		return bucketHashParams{}, fmt.Errorf(
			"lz: invalid bucketSize in bucketHash name: %s", name)
	}

	if err = p.verify(); err != nil {
		return bucketHashParams{}, err
	}

	return p, nil
}

// newBucketHash allocates and initializes a bucketHash according to the
// provided parameters.
func newBucketHash(p bucketHashParams) (*bucketHash, error) {
	h := &bucketHash{}
	if err := h.init(p); err != nil {
		return nil, err
	}
	return h, nil
}

// init initializes the internal storage and derived fields of the bucket
// hash (mask and shift). It allocates the buckets and index arrays.
func (bh *bucketHash) init(p bucketHashParams) error {
	var err error
	if err = p.verify(); err != nil {
		return err
	}

	n := 1 << p.hashBits
	*bh = bucketHash{
		buckets:    make([]Entry, n*p.bucketSize),
		indexes:    make([]byte, n),
		mask:       1<<(p.inputLen*8) - 1,
		shift:      64 - uint(p.hashBits),
		inputLen:   p.inputLen,
		hashBits:   p.hashBits,
		bucketSize: p.bucketSize,
	}
	return nil
}

// InputLen returns the number of input bytes the bucket hash uses for its
// hash computation.
func (bh *bucketHash) InputLen() int { return bh.inputLen }

// Reset resets the bucket hash to its initial empty state by zeroing the
// internal buckets and index arrays. Configuration fields such as
// inputLen, hashBits and bucketSize are preserved. Reset is not safe for
// concurrent use and should be called when the mapper is not in use.
func (bh *bucketHash) Reset() {
	for i := range bh.buckets {
		bh.buckets[i] = Entry{}
	}
	for i := range bh.indexes {
		bh.indexes[i] = 0
	}
}

// bucket returns a slice view into the underlying bucket storage for the
// given hash index h.
func (bh *bucketHash) bucket(h uint32) []Entry {
	k := int(h) * bh.bucketSize
	return bh.buckets[k : k+bh.bucketSize]
}

// Shift advances the window by delta bytes: positions stored in the
// entries are reduced by delta and entries that fall below zero are
// discarded. delta must be > 0 and not exceed math.MaxUint32.
func (bh *bucketHash) Shift(delta int) {
	if delta <= 0 {
		return
	}
	if delta >= math.MaxUint32 {
		panic("lz: delta too large")
	}
	delta32 := uint32(delta)
	tmp := make([]Entry, bh.bucketSize)
	for h, j := range bh.indexes {
		b := bh.bucket(uint32(h))
		i := 0
		for _, e := range b[j:] {
			if e.i < delta32 {
				continue
			}
			e.i -= delta32
			tmp[i] = e
			i++
		}
		for _, e := range b[:j] {
			if e.i < delta32 {
				continue
			}
			e.i -= delta32
			tmp[i] = e
			i++
		}
		copy(b, tmp[:i])
		if i >= bh.bucketSize {
			i = 0
		} else {
			p := b[i:]
			for k := range p {
				p[k] = Entry{}
			}
		}
		bh.indexes[h] = byte(i)
	}
}

// Put inserts entries for the byte sequence p. It starts at position a and
// attempts to add up to w bytes; it returns the number of bytes that could
// not be processed because they are too close to the end of p.
func (bh *bucketHash) Put(p []byte, a, w int) int {
	b := min(w, max(len(p)-max(bh.inputLen, 4)+1, 0))
	_p := p[:b+7]
	for i := a; i < b; i++ {
		v := _getLE64(_p[i:])
		h := hashValue(v&bh.mask, bh.shift)
		pidx := &bh.indexes[h]
		idx := int(*pidx)
		k := int(h)*bh.bucketSize + idx
		bh.buckets[k] = Entry{i: uint32(i), v: uint32(v)}
		idx++
		if idx >= bh.bucketSize {
			idx = 0
		}
		*pidx = byte(idx)
	}
	return w - b
}

// AppendEntries appends candidate Entry values for the provided value v
// from the corresponding bucket. Only entries whose masked value matches are
// appended.
func (bh *bucketHash) AppendEntries(entries []Entry, v uint64) []Entry {
	v &= bh.mask
	h := hashValue(v, bh.shift)
	b := bh.bucket(h)
	for _, e := range b {
		if e.v&uint32(bh.mask) == uint32(v) && e != (Entry{}) {
			entries = append(entries, e)
		}
	}
	return entries
}
