name: Go Test

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test (${{ matrix.goarch }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        goarch: [amd64, 386]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Run tests
        env:
          GOARCH: ${{ matrix.goarch }}
          CGO_ENABLED: 0
        run: go test ./...
