name: "Go Vulnerability Check"

on:
  schedule:
    # Run once a week on Friday at 2:15 AM CEST (12:15 AM UTC)
    - cron: '15 0 * * 5'
  workflow_dispatch:

jobs:
  govulncheck:
    name: Run govulncheck
    runs-on: ubuntu-latest
    steps:
      - name: Run govulncheck
        uses: golang/govulncheck-action@v1
        with:
          go-package: ./...
